/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as OutstationRouteImport } from './routes/outstation'
import { Route as IndexRouteImport } from './routes/index'

const OutstationRoute = OutstationRouteImport.update({
  id: '/outstation',
  path: '/outstation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/outstation': typeof OutstationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/outstation': typeof OutstationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/outstation': typeof OutstationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/outstation'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/outstation'
  id: '__root__' | '/' | '/outstation'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OutstationRoute: typeof OutstationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/outstation': {
      id: '/outstation'
      path: '/outstation'
      fullPath: '/outstation'
      preLoaderRoute: typeof OutstationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OutstationRoute: OutstationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
